export * from './DocumentClass';
export * from './DocumentFunction';
export * from './DocumentInterface';
export * from './DocumentObject';
export * from './DocumentEnum';
export * from './DocumentBasic';
export * from './DocumentIntersection';
export * from './DocumentUnion';
export * from './DocumentArray';
export * from './DocumentTuple';
// export * from './DocumentTypeAlias';
